import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createSupabaseClient, corsHeaders, handleCors } from './_shared.ts';
import OpenAI from 'https://esm.sh/openai@6.1.0';
import { GoogleGenerativeAI } from 'https://esm.sh/@google/generative-ai@0.24.1';

serve(async (req) => {
  const corsResponse = handleCors(req);
  if (corsResponse) return corsResponse;

  if (req.method !== 'POST') {
    return new Response(JSON.stringify({ error: 'Method not allowed' }), {
      status: 405,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  try {
    const supabase = createSupabaseClient(req);
    const body = await req.json();
    const { userId } = body;

    if (!userId) {
      return new Response(JSON.stringify({ error: 'userId required' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const { data: profile, error: profileErr } = await supabase
      .from('profiles')
      .select('plan, plan_expiry')
      .eq('id', userId)
      .single();

    if (profileErr) {
      return new Response(JSON.stringify({ error: 'Profile not found' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const now = new Date();
    // Allow trial users and active subscriptions
    const hasActiveTrial = profile?.plan === 'trial' && profile?.plan_expiry && new Date(profile.plan_expiry) > now;
    const hasActivePlan = profile?.plan && profile.plan !== 'trial' && (!profile?.plan_expiry || new Date(profile.plan_expiry) > now);
    const active = hasActiveTrial || hasActivePlan;
    
    if (!active) {
      return new Response(JSON.stringify({ error: 'AI Coach requires an active subscription or trial' }), {
        status: 403,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const { data: details } = await supabase
      .from('onboarding_details')
      .select('*')
      .eq('user_id', userId)
      .maybeSingle();

    const makeBasePlan = (summary: string) => ({
      generatedAt: new Date().toISOString(),
      summary,
      goals: details?.goals || [],
      weeks: 4,
      schedule: [
        { day: 'Mon', workout: 'Full-body strength', nutrition: 'High protein, balanced carbs', mindfulness: '10m breathing' },
        { day: 'Tue', workout: 'Zone 2 cardio 30m', nutrition: 'Mediterranean plate', mindfulness: 'Body scan 10m' },
        { day: 'Wed', workout: 'Mobility + core', nutrition: 'Balanced bowl', mindfulness: 'Gratitude journaling' },
        { day: 'Thu', workout: 'Upper strength', nutrition: 'High protein', mindfulness: 'Box breathing 8m' },
        { day: 'Fri', workout: 'Intervals 20m', nutrition: 'Complex carbs focus', mindfulness: 'Mindful walk' },
        { day: 'Sat', workout: 'Lower strength', nutrition: 'Protein + greens', mindfulness: 'Meditation 12m' },
        { day: 'Sun', workout: 'Rest / light yoga', nutrition: 'Free choice within macros', mindfulness: 'Reflection 10m' },
      ],
      personalization: {
        injuries: details?.injuries || [],
        allergies: details?.allergies || [],
        meditationExperience: details?.meditation_experience || 'beginner',
      }
    });

    const geminiKey = Deno.env.get('GEMINI_API_KEY');
    const openaiKey = Deno.env.get('OPENAI_KEY');
    const summaries = {
      fitness: 'AI Fitness Plan - 4 weeks',
      nutrition: 'AI Nutrition Plan - 4 weeks',
      mental: 'AI Mental Health Plan - 4 weeks',
    } as const;

    const buildPrompt = (domain: 'fitness' | 'nutrition' | 'mental') => ({
      system: `You are a world-class ${domain} coach. Create a 4-week ${domain} plan.`,
      user: `User goals: ${JSON.stringify(details?.goals || [])}
Allergies: ${JSON.stringify(details?.allergies || [])}
Injuries: ${JSON.stringify(details?.injuries || [])}
Meditation experience: ${JSON.stringify(details?.meditation_experience || 'beginner')}
Return JSON with fields: generatedAt (ISO), summary (string), goals (array), weeks (number), schedule (array of 7 objects relevant to ${domain}), personalization (object).`,
    });

    const result: any[] = [];
    const categories: Array<{ key: 'fitness'|'nutrition'|'mental'; category: 'fitness'|'nutrition'|'mental health' }> = [
      { key: 'fitness', category: 'fitness' },
      { key: 'nutrition', category: 'nutrition' },
      { key: 'mental', category: 'mental health' },
    ];

    if (!geminiKey && !openaiKey) {
      for (const c of categories) {
        const plan = makeBasePlan(summaries[c.key]);
        const { data: inserted } = await supabase
          .from('programs')
          .insert({
            name: plan.summary,
            description: `Personalized ${plan.weeks}-week plan generated by AI`,
            status: 'active',
            category: c.category,
            coach_id: userId,
            assigned_to: userId,
            scheduled_date: new Date().toISOString(),
            plan,
            is_ai_generated: true,
          })
          .select('id, category')
          .single();
        result.push({ category: c.category, programId: inserted?.id, status: 'ready', source: 'base' });
      }
      return new Response(JSON.stringify({ items: result }), {
        status: 200,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    try {
      if (geminiKey) {
        const genAI = new GoogleGenerativeAI(geminiKey);
        for (const c of categories) {
          const { system, user } = buildPrompt(c.key);
          const prompt = `${system}\n\n${user}\n\nReturn only valid JSON.`;
          const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });
          const response = await model.generateContent(prompt);
          const text = response.response.text();
          const plan = JSON.parse(text);
          const { data: inserted } = await supabase
            .from('programs')
            .insert({
              name: plan.summary || summaries[c.key],
              description: `Personalized ${plan.weeks || 4}-week plan generated by AI`,
              status: 'active',
              category: c.category,
              coach_id: userId,
              assigned_to: userId,
              scheduled_date: new Date().toISOString(),
              plan,
              is_ai_generated: true,
            })
            .select('id, category')
            .single();
          result.push({ category: c.category, programId: inserted?.id, status: 'ready', source: 'gemini' });
        }
      } else {
        const client = new OpenAI({ apiKey: openaiKey as string });
        for (const c of categories) {
          const { system, user } = buildPrompt(c.key);
          const completion = await client.chat.completions.create({
            model: 'gpt-4o-mini',
            messages: [
              { role: 'system', content: system },
              { role: 'user', content: user },
            ],
            response_format: { type: 'json_object' },
            temperature: 0.7,
          });
          const content = completion.choices?.[0]?.message?.content || '';
          const plan = JSON.parse(content);
          const { data: inserted } = await supabase
            .from('programs')
            .insert({
              name: plan.summary || summaries[c.key],
              description: `Personalized ${plan.weeks || 4}-week plan generated by AI`,
              status: 'active',
              category: c.category,
              coach_id: userId,
              assigned_to: userId,
              scheduled_date: new Date().toISOString(),
              plan,
              is_ai_generated: true,
            })
            .select('id, category')
            .single();
          result.push({ category: c.category, programId: inserted?.id, status: 'ready', source: 'openai' });
        }
      }
      return new Response(JSON.stringify({ items: result }), {
        status: 200,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    } catch (llmErr: any) {
      for (const c of categories) {
        const plan = makeBasePlan(summaries[c.key]);
        const { data: inserted } = await supabase
          .from('programs')
          .insert({
            name: plan.summary,
            description: `Personalized ${plan.weeks}-week plan generated by AI`,
            status: 'active',
            category: c.category,
            coach_id: userId,
            assigned_to: userId,
            scheduled_date: new Date().toISOString(),
            plan,
            is_ai_generated: true,
          })
          .select('id, category')
          .single();
        result.push({ category: c.category, programId: inserted?.id, status: 'processing', source: 'base' });
      }
      return new Response(JSON.stringify({ items: result }), {
        status: 200,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }
  } catch (e: any) {
    console.error('[AI] generate-plans error', e);
    return new Response(JSON.stringify({ error: e?.message || 'Failed to generate plans' }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});

