// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { config } from '@/lib/config';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Force production URLs for auth redirects
const authOptions = {
  storage: localStorage,
  persistSession: true,
  autoRefreshToken: true,
  // Override redirect URLs to force production domain (match Supabase Site URL)
  ...(import.meta.env.PROD && {
    redirectTo: 'https://www.trainwisestudio.com'
  })
};

export const supabase = createClient(config.supabase.url, config.supabase.anonKey, {
  auth: authOptions
});